name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
      - name: RunMavenTest
  # You may pin to the exact commit or the version.
  # uses: Maes95/maven-action@69c270aa2d7d371b74a888e3248af909f840585a
        uses: Maes95/maven-action@1.0.0
        with:
    # If true, build jar of the project
          package: false
